apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
      - name: minecraft-server-data
        persistentVolumeClaim:
          claimName: minecraft-server-data
      containers:
      - name: minecraft-server
        image: openjdk:18-slim-buster
        volumeMounts:
        - mountPath: "/src"
          name: minecraft-server-data
        ports:
        - containerPort: 25565
        stdin: true
        tty: true
        workingDir: /src
        command: ["java"]
        args: ["-Xmx14G", "-Xms14G", "-jar", "server.jar", "nogui"]
---

apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 25565
      targetPort: 25565
