apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
      - name: minecraft-server-data
        persistentVolumeClaim:
          claimName: minecraft-server-data
      containers:
      - name: minecraft-server
        image: openjdk:17-slim-buster
        volumeMounts:
        - mountPath: "/src"
          name: minecraft-server-data
        ports:
        - containerPort: 25565
        stdin: true
        tty: true
        workingDir: /src
        command: ["java"]
        args: ["-Xms2G", "-Xmx12G", "-XX:+UseG1GC", "-jar", "spigot-1.18.1.jar", "nogui"]
---

apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 25565
      targetPort: 25565

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-bedrock
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 19132
      targetPort: 19132
      protocol: UDP
