apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-server-data
  labels:
    type: local
spec:
  storageClassName: minecraft-server-data
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/minecraft-server-data"